# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos del backend al directorio de trabajo
COPY api.py .

# Instala las dependencias necesarias
RUN pip install flask

# Expone el puerto en el que tu aplicación escuchará
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "api.py"]
