# Usa la última imagen de Ubuntu
FROM ubuntu:latest

# Actualiza y actualiza los paquetes
RUN apt-get update && apt-get upgrade -y

# Comando por defecto para ejecutar al iniciar el contenedor
CMD echo "Hello, World!"
